macro (create_app_key APP_NAME)
    if (UNIX)
        find_program(KEYTOOL "keytool")
        if (KEYTOOL)
            if (NOT EXISTS ${ANDROID_STUDIO_PROJ}/${APP_NAME}_key.jks)
                execute_process(COMMAND keytool -genkey -v -keystore ${ANDROID_STUDIO_PROJ}/${APP_NAME}_key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias ${APP_NAME} -dname "cn=Unknown, ou=Unknown, o=Unknown, c=Unknown" -storepass ${SIGN_KEY_PASS} -keypass ${SIGN_KEY_PASS})
            endif()
        else()
            message(WARNING "keytool does not exist on this system. can't generate a key for signing")
        endif()
    elseif (WIN32)
        if (EXISTS $ENV{ProgramFiles}/Android/Android\ Studio/jbr/bin/keytool.exe)
            execute_process(COMMAND $ENV{ProgramFiles}/Android/Android\ Studio/jbr/bin/keytool.exe -genkey -v -keystore ${ANDROID_STUDIO_PROJ}/${APP_NAME}_key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias ${APP_NAME} -dname "cn=Unknown, ou=Unknown, o=Unknown, c=Unknown" -storepass ${SIGN_KEY_PASS} -keypass ${SIGN_KEY_PASS})
        elseif (EXISTS $ENV{ProgramFiles}/Android/Android\ Studio/jre/keytool.exe)
                execute_process(COMMAND $ENV{ProgramFiles}/Android/Android\ Studio/jre/keytool.exe -genkey -v -keystore ${ANDROID_STUDIO_PROJ}/${APP_NAME}_key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias ${APP_NAME} -dname "cn=Unknown, ou=Unknown, o=Unknown, c=Unknown" -storepass ${SIGN_KEY_PASS} -keypass ${SIGN_KEY_PASS})
        endif()
    endif()
endmacro()