include(Android/CreateMainActivity)
include(Android/CreateSplashActivity)
include(Android/CreateCustomGLSurfaceView)
include(Android/CreateJNIInterface)
include(Android/CreateCameraPermissionHelper)

macro(create_app_java_sources app_type ADMOB_UNIT_ID)
    create_main_activity(${app_type} ${ADMOB_UNIT_ID})
    create_custom_glsurfaceview(${app_type})
    create_splashscreen_activity(${app_type})
    create_jni_interface()
    if(ARA_USE_ARCORE)
        create_camera_permission_helper()
    endif ()
endmacro()