if (NOT DEFINED ARA_USE_ARCORE)
    set(ARA_USE_ARCORE OFF)
endif()
if (NOT DEFINED ARA_USE_ASSIMP)
    set(ARA_USE_ASSIMP ON)
endif()
if (NOT DEFINED ARA_USE_CURL)
    set(ARA_USE_CURL ON)
endif()
if (NOT DEFINED ARA_USE_CMRC)
    set(ARA_USE_CMRC ON)
endif()
if (NOT DEFINED ARA_USE_FREEIMAGE)
    set(ARA_USE_FREEIMAGE ON)
endif()
if (NOT DEFINED ARA_USE_FFMPEG)
    set(ARA_USE_FFMPEG ON)
endif()
if (NOT DEFINED ARA_USE_GLBASE)
    set(ARA_USE_GLBASE ON)
endif()
if (NOT DEFINED ARA_USE_MEDIACODEC)
    set(ARA_USE_MEDIACODEC OFF)
endif()
if (NOT DEFINED ARA_USE_NDI)
    set(ARA_USE_NDI OFF)
endif()
if (NOT DEFINED ARA_USE_OBS)
    set(ARA_USE_OBS OFF)
endif()
if (NOT DEFINED ARA_USE_OPENAL)
    set(ARA_USE_OPENAL OFF)
endif()
if (NOT DEFINED ARA_USE_OPENCV)
    set(ARA_USE_OPENCV OFF)
endif()
if (NOT DEFINED ARA_USE_PORTAUDIO)
    set(ARA_USE_PORTAUDIO ON) # causes lldb crash ...
endif()
if (NOT DEFINED ARA_USE_REALSENSE)
    set(ARA_USE_REALSENSE OFF)
endif ()

if (ANDROID)
    if (NOT DEFINED ARA_USE_ARCORE)
        set(ARA_USE_ARCORE ON)
    endif ()
    set(ARA_USE_MEDIACODEC ON)
    set(ARA_USE_REALSENSE OFF)
    set(ARA_ANDROID_PURE_NATIVE_APP OFF)
    set(ARA_USE_GLFW OFF)
    set(ARA_USE_CMRC ON)
    set(ARA_USE_EGL ON)
    set(ARA_USE_GLES31 ON)
else()
    set(ARA_USE_GLFW ON)
    set(ARA_USE_EGL OFF)
    set(ARA_USE_GLES31 OFF)
endif()


# translate cmake switches to preprocessor flags - nothing to do configure manually here

if (ARA_USE_CMRC AND NOT ${CMAKE_BUILD_TYPE} MATCHES Debug OR ANDROID)
    add_compile_definitions(ARA_USE_CMRC)
endif()
if (ARA_USE_CURL)
    add_compile_definitions(ARA_USE_CURL)
endif()
if (ARA_USE_EGL)
    add_compile_definitions(ARA_USE_EGL)
endif()
if (ARA_USE_GLFW AND NOT COMPILE_SCENEGRAPH_LIB_NO_GLFW)
    add_compile_definitions(ARA_USE_GLFW)
endif()
if (ARA_USE_GLES31)
    add_compile_definitions(ARA_USE_GLES31)
endif()
if (ARA_USE_REALSENSE)
    add_compile_definitions(ARA_USE_REALSENSE)
endif()
if (ARA_USE_FFMPEG)
    add_compile_definitions(ARA_USE_FFMPEG)
endif()
if (ARA_USE_OPENAL)
    add_compile_definitions(ARA_USE_OPENAL)
endif()
if (ANDROID AND ARA_USE_ARCORE)
    add_compile_definitions(ARA_USE_ARCORE)
endif()
if (ARA_USE_FREEIMAGE)
    add_compile_definitions(ARA_USE_FREEIMAGE)
endif ()
if (ARA_USE_OPENCV)
    add_compile_definitions(ARA_USE_OPENCV)
    if(WIN32)
        set(OpenCV_DIR ${CMAKE_SOURCE_DIR}/Libraries/third_party/opencv/x64/vc16/lib)
    endif ()
endif()
if (ARA_USE_PORTAUDIO)
    add_compile_definitions(ARA_USE_PORTAUDIO)
endif()
if (ARA_USE_NDI)
    add_compile_definitions(ARA_USE_NDI)
endif()
if (${ARA_ANDROID_PURE_NATIVE_APP})
    add_compile_definitions(ARA_ANDROID_PURE_NATIVE_APP)
endif()

set(COMPILE_SCENEGRAPH_LIB OFF)           # standalone compilation of UI Framework
set(COMPILE_SCENEGRAPH_LIB_NO_GLFW OFF)   # compile without glfw
set(COMPILE_SCENEGRAPH_LIB_STATIC OFF)    # compile with MTd / MT switch for windows

if (COMPILE_SCENEGRAPH_LIB)
    add_compile_definitions(ARA_USE_GLBASE)
endif ()

if (${CMAKE_BUILD_TYPE} MATCHES Debug)
    add_compile_definitions(ARA_DEBUG)
endif()
