# this is the general cmake file to be used when including this project into another cmake project

set(ARA_SDK_SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}/../../../)
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

include(AraConfigure)

include(GLBaseDepInclude)
include(GLBaseDependencies)
include(GLBaseCopyDependencies)
include(VideoInputDepInclude)
include(VideoInputCopyDependencies)
include(VideoInputDependencies)
include(Gtk3Include)
include(ResCompInclude)
include(PugiXMLInclude)
include(UtilitiesDepInclude)
include(UtilitiesDependencies)
include(OpenCV)


macro(add_ara_doc_link_to_readme)
    set(README_PATH "${CMAKE_SOURCE_DIR}/README.md")
    if(EXISTS "${README_PATH}")
        file(READ "${README_PATH}" README_CONTENT)
        string(REPLACE "\n" ";" line_list ${README_CONTENT})
        foreach(line IN LISTS line_list)
            string(FIND "${line}" "[ARA SDK Documentation]" found_docu_string)
            if (${found_docu_string} EQUAL -1)
                LIST(APPEND NEW_README_CONTENT "${line}\n")
                string(FIND "${line}" "### ara sdk" index)
                if (${index} GREATER -1)
                    LIST(APPEND NEW_README_CONTENT "[ARA SDK Documentation](${ARA_SDK_SOURCE_DIR}/README.md)\n")
                endif ()
            endif ()
        endforeach ()
        LIST(POP_BACK NEW_README_CONTENT)
        file(WRITE "${README_PATH}" ${NEW_README_CONTENT})
    else()
        message(WARNING "README.md does not exist in the root directory.")
    endif()
endmacro()
add_ara_doc_link_to_readme()