set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
set(ARA_SDK_TARGET_LINK_OPTS)

include(AraSdkConfigure)
include(AraSdkMacros)
include(GeneralSettings)
include(VisualStudioSettings)
include(CMakeRC)

include(GLBaseDepInclude)
include(GLBaseDependencies)
include(GLBaseCopyDependencies)
include(Gtk3Include)
include(ResCompInclude)
include(PugiXMLInclude)
include(UIDepInclude)
include(UtilitiesDepInclude)
include(UtilitiesDependencies)
include(UtilitiesCopyDependencies)
include(OpenCV)

if (ARA_USE_CMRC AND NOT ${CMAKE_BUILD_TYPE} MATCHES Debug OR ANDROID)
    add_compile_definitions(ARA_USE_CMRC)
endif()
if (ARA_USE_CURL)
    add_compile_definitions(ARA_USE_CURL)
endif()
if (ARA_USE_EGL)
    add_compile_definitions(ARA_USE_EGL)
endif()
if (ARA_USE_GLFW AND NOT COMPILE_SCENEGRAPH_LIB_NO_GLFW)
    add_compile_definitions(ARA_USE_GLFW)
endif()
if (ARA_USE_GLES31)
    add_compile_definitions(ARA_USE_GLES31)
endif()
if (ARA_USE_FREEIMAGE)
    add_compile_definitions(ARA_USE_FREEIMAGE)
endif ()
if (ARA_USE_OPENCV)
    add_compile_definitions(ARA_USE_OPENCV)
    if(WIN32)
        set(OpenCV_DIR ${CMAKE_SOURCE_DIR}/Libraries/third_party/opencv/x64/vc16/lib)
    endif ()
endif()
if (${ARA_ANDROID_PURE_NATIVE_APP})
    add_compile_definitions(ARA_ANDROID_PURE_NATIVE_APP)
endif()

set(COMPILE_SCENEGRAPH_LIB OFF)           # standalone compilation of UI Framework
set(COMPILE_SCENEGRAPH_LIB_NO_GLFW OFF)   # compile without glfw
set(COMPILE_SCENEGRAPH_LIB_STATIC OFF)    # compile with MTd / MT switch for windows

if (COMPILE_SCENEGRAPH_LIB)
    add_compile_definitions(ARA_USE_GLBASE)
endif ()

if (${CMAKE_BUILD_TYPE} MATCHES Debug)
    add_compile_definitions(ARA_DEBUG)
endif()
