macro(add_ara_doc_link_to_readme)
    set(README_PATH "${CMAKE_SOURCE_DIR}/README.md")
    if(EXISTS "${README_PATH}")
        file(READ "${README_PATH}" README_CONTENT)
        string(REPLACE "\n" ";" line_list ${README_CONTENT})
        foreach(line IN LISTS line_list)
            string(FIND "${line}" "[ARA SDK Documentation]" found_docu_string)
            if (${found_docu_string} EQUAL -1)
                LIST(APPEND NEW_README_CONTENT "${line}\n")
                string(FIND "${line}" "### ara sdk" index)
                if (${index} GREATER -1)
                    LIST(APPEND NEW_README_CONTENT "[ARA SDK Documentation](${ARA_SDK_SOURCE_DIR}/README.md)\n")
                endif ()
            endif ()
        endforeach ()
        LIST(POP_BACK NEW_README_CONTENT)
        file(WRITE "${README_PATH}" ${NEW_README_CONTENT})
    else()
        message(WARNING "README.md does not exist in the root directory.")
    endif()
endmacro()

macro(create_symlink in_target in_linkname)
    if (APPLE)
        execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${in_target} ${in_linkname})
    elseif(UNIX)
        execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${in_target} ${in_linkname})
    elseif(WIN32)
        file(TO_NATIVE_PATH ${in_target} target)
        file(TO_NATIVE_PATH ${in_linkname} link)
        execute_process(COMMAND cmd /c ${ARA_SDK_SOURCE_DIR}\\scripts\\create_symlink.bat ${link} ${target})
    endif()
endmacro()

function(append_unique list_name)
    foreach(item IN LISTS ARGN)
        list(FIND ${list_name} "${item}" _index)
        if(_index EQUAL -1)
            list(APPEND ${list_name} "${item}")
        endif()
    endforeach()
    # Update the caller's scope
    set(${list_name} "${${list_name}}" PARENT_SCOPE)
endfunction()