macro(create_symlink in_target in_linkname)
    if (APPLE)
        execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${in_target} ${in_linkname})
    elseif(UNIX)
        execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${in_target} ${in_linkname})
    elseif(WIN32)
        file(TO_NATIVE_PATH ${in_target} target)
        file(TO_NATIVE_PATH ${in_linkname} link)
        execute_process(COMMAND cmd /c ${CMAKE_SOURCE_DIR}\\create_symlink.bat ${link} ${target})
    endif()
endmacro()