include(${ARA_SDK_SOURCE_DIR}/Libraries/cmake/Modules/AraSdkMacros.cmake)

if (UNIX AND NOT APPLE AND NOT ANDROID)
	find_package(PkgConfig REQUIRED)
	pkg_check_modules(GTK3 REQUIRED gtk+-3.0)
	if (GTK3_FOUND)
		append_unique(ara_sdk_INCLUDE_DIRS ${GTK3_INCLUDE_DIRS})
		link_directories(${GTK3_LIBRARY_DIRS})
		add_definitions(${GTK3_CFLAGS_OTHER})
		append_unique(ara_sdk_LIBRARIES ${GTK3_LIBRARIES})
	endif (GTK3_FOUND)
endif()
