if (ARA_USE_OPENCV)
    if (WIN32)
        append_unique(ara_sdk_BINARIES ${CMAKE_SOURCE_DIR}/Libraries/third_party/opencv/x64/vc16/bin/opencv_videoio_ffmpeg4100_64.dll)
        if (${CMAKE_BUILD_TYPE} MATCHES Debug)
            append_unique(ara_sdk_BINARIES ${CMAKE_SOURCE_DIR}/Libraries/third_party/opencv/x64/vc16/bin/opencv_world4100d.dll)
        else ()
            append_unique(ara_sdk_BINARIES ${CMAKE_SOURCE_DIR}/Libraries/third_party/opencv/x64/vc16/bin/opencv_world4100.dll)
        endif ()
    else ()
        find_package(OpenCV REQUIRED PATHS "..")
        if (OPENCV_FOUND)
            include_directories( ${OpenCV_INCLUDE_DIRS} )
        endif ()
    endif()
endif()